-- SQL script to insert dummy data into BANK_MICRO_DB
INSERT INTO BANK_MICRO_DB (BANK_NAME, IFSC_CODE, BRANCH_NAME, BRANCH_ADDRESS) VALUES ('State Bank of India', 'SBIN0001234', 'MG Road', '123 MG Road, Mumbai');
INSERT INTO BANK_MICRO_DB (BANK_NAME, IFSC_CODE, BRANCH_NAME, BRANCH_ADDRESS) VALUES ('HDFC Bank', 'HDFC0005678', 'Andheri', '456 Andheri West, Mumbai');
INSERT INTO BANK_MICRO_DB (BANK_NAME, IFSC_CODE, BRANCH_NAME, BRANCH_ADDRESS) VALUES ('ICICI Bank', 'ICIC0009101', 'Bandra', '789 Bandra East, Mumbai');
INSERT INTO BANK_MICRO_DB (BANK_NAME, IFSC_CODE, BRANCH_NAME, BRANCH_ADDRESS) VALUES ('Axis Bank', 'UTIB0002345', 'Powai', '101 Powai Lake, Mumbai');

