spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    bus:
      enabled: true
      kafka:
        binder:
          brokers: localhost:9092